[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[build.processing]
  skip_processing = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Simplified redirects - this will handle all paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = {}}
